development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: auditorium_development
  pool: 5
  username: auditorium
  password: veryverysecret

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: auditorium_test
  pool: 5
  username: auditorium
  password: veryverysecret

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: auditorium_production
  pool: 5
  username: auditorium
  password: veryverysecret
