development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: auditorium_development
  pool: 5
  username: root
  password: veryverysecret

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: auditorium_test
  pool: 5
  username: root
  password: veryverysecret

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: auditorium_production
  pool: 5
  username: root
  password: veryverysecret
